    <?php if (!isset($_SESSION['user_loggedIn'])) { ?>
    <div class="fixed-bottom d-flex flex-wrap justify-content-center align-items-center card shadow">
        <div class="text">
            <p class="fs-2 align"><strong>See more of this website</strong></p>
        </div>
        <div id="buttons">
            <a class="btn btn-primary btn-lg align" href="../Controller/login.php">Log in</a>
            or
            <a class="btn btn-success btn-lg align" href="../Controller/register.php">Create new account</a>
        </div>
    </div>
    <?php } ?>

<!-- Boostrap JavaScript Bundle with Popper Positioning Engine-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous">

    </script>
</body>
</html>
