<?php require('Template/header.phtml') ?>

<link rel="stylesheet" href="../Styles/search-page.css">
<div id="profile-div" class="container justify-content-center align-items-center">
    <div class="wrapper bg-white mt-sm-5">

        <?php if (isset($_SESSION['error'])) { ?>
            <div class="alert alert-danger" role="alert">
                <?php echo $_SESSION['error']; ?>
            </div>
        <?php } ?>

        <h4 class="text-center">Your friends list</h4>

        <?php if (isset($_SESSION['user_loggedIn'])) { ?>
        <div class="text-center">
            <a href="../Controller/live_map.php" id="live-map-btn" class="btn btn-large btn-primary text-center">View your friends live location</a>
        </div>
        <div class="row">
            <?php if ($view->friendsList != 0) {
                foreach ($view->friendsList as $friendData) { ?>
            <div class="col-xxl-6 col-sm-12 mb-4">
                <div class="card text-center" onclick="location.href='../Controller/user_profile.php?usr=<?php echo $friendData->getUserID() ?>';">
                    <img src="<?php echo htmlentities($friendData->getPhoto()); ?>" class="card-img-top rounded" alt="profile-img">
                    <div class="card-body">
                        <h5 class="card-title"><?php echo htmlentities($friendData->getUsername()); ?></h5>
                        <h6 class="card-subtitle mb-2 text-muted"><?php echo htmlentities($friendData->getFullName()); ?></h6>
                        <p class="card-text">Location: ( <?php echo $friendData->getLatitude().' , '.$friendData->getLongitude() ?>)</p>
                        <a href="../Controller/request_functions.php?request=unfriend&id=<?php echo $friendData->getUserID(); ?>" class="btn btn-danger btn-sm">Unfriend</a>
                    </div>
                </div>
            </div>
            <?php }} else echo '<h6 class="text-center">You currently have no friends</h6>' ?>
        </div>
        <?php } else echo '<h3 class="text-center">You are not logged in!</h3>' ?>
    </div>
</div>

<?php if (isset($_SESSION['error'])) unset($_SESSION['error']) ?>
<?php require('Template/footer.phtml') ?>