<?php require('Template/header.phtml') ?>

<link rel="stylesheet" href="../Styles/search-page.css">

<!-- Leaflet CSS -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin=""/>

<!-- Leaflet Plugin CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.76.1/dist/L.Control.Locate.min.css" />

<!-- Leaflet JS File -->
<script defer src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
        integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
        crossorigin=""></script>

<script defer src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.76.1/dist/L.Control.Locate.min.js" charset="utf-8"></script>

<!-- Live Map Script -->
<script defer type="module" src="../Scripts/live-map.js"></script>

<!-- Live Map Update Friends Location Script -->
<script defer type="module" src="../Scripts/live-map-update.js"></script>

<div id="profile-div" class="container justify-content-center align-items-center">
    <div class="wrapper bg-white mt-sm-5">

        <?php if (isset($_SESSION['error'])) { ?>
            <div class="alert alert-danger" role="alert">
                <?php echo $_SESSION['error']; ?>
            </div>
        <?php } ?>

        <h3 class="text-center"><?php echo $view->pageTitle ?><svg height="50" width="50" id="blinking"><circle cx="20" cy="25" r="11" fill="red"/></svg></h3>

        <?php if (isset($_SESSION['user_loggedIn'])) { ?>
        <!-- Live Map Here -->
        <div id="map">

        </div>
        <?php } else echo '<h3 class="text-center">You are not logged in!</h3>' ?>
    </div>
</div>

<?php if (isset($_SESSION['error'])) unset($_SESSION['error']) ?>
<?php require('Template/footer.phtml') ?>
