<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous"
    />
    <!-- Icon Fonts Stylesheet -->
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css"
    />

    <title><?php echo $view->pageTitle; ?></title>
</head>
<body class="bg-light bg-gradient">
<div class="container">
    <div class="row justify-content-center mt-5 pt-5">
        <div class="col-lg-4 col-md-8 col-sm-8">
            <?php if (isset($_SESSION['error'])) { ?>
            <div class="alert alert-danger" role="alert">
                <?php echo $_SESSION['error']; ?>
            </div>
            <?php } ?>
            <div class="card shadow">
                <div class="card-title text-center border-bottom">
                    <h2 class="p-3">Log in</h2>
                </div>
                <div class="card-body">
                    <form action="../Controller/login.php" method="POST">
                        <div class="mb-4">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" REQUIRED/>
                        </div>
                        <div class="mb-4">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" REQUIRED/>
                        </div>

                        <p class="fw-light">
                            Don't have an account? <a href="../Controller/register.php">Register here</a>
                        </p>

                        <div class="d-grid">
                            <button type="submit" name="submit" class="btn btn-success">Log in</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php if (isset($_SESSION['error'])) unset($_SESSION['error']) ?>
</body>
</html>

