<?php require('Template/header.phtml'); ?>

<!-- Profile Settings html -->
<link rel="stylesheet" href="../Styles/profile-settings.css">
<div id="profile-div" class="container justify-content-center align-items-center">
    <div class="wrapper bg-white mt-sm-5">
        <?php if (isset($_SESSION['error'])) { ?>
        <div class="alert alert-danger" role="alert">
            <?php echo $_SESSION['error']; ?>
        </div>
        <?php } ?>
        <h4 class="pb-4 border-bottom">Profile settings</h4>
        <?php if (isset($_SESSION['user_loggedIn'])) {
            foreach ($view->usersDataSet as $userData) {
                if ($_SESSION['user_loggedIn'] == $userData->getUsername()) { ?>
        <div class="d-flex align-items-start py-3 border-bottom"> <img src="<?php echo htmlentities($userData->getPhoto()); ?>" class="img border" alt="profile-img">
            <div class="pl-sm-4 pl-2" id="img-section"> <b>Profile Photo</b>
                <p>Accepted file types .png .jpg. .jpeg, Less than 1MB (Equal height/width recommended)</p>
                <!-- Profile image upload form -->
                <form enctype="multipart/form-data" action="../Controller/upload.php" method="POST">
                    <!-- Maximum file size for upload (<1 MB) -->
                    <input type="hidden" name="MAX_FILE_SIZE" value="999999" />
                    <input type="file" name="FILE" required>
                    <br><button class="btn button border mt-2" type="submit" name="submit" value="Send File"><b>Upload</b></button>
                </form>
            </div>
        </div>
        <div class="py-2">
            <div class="row py-2">
                <div class="col-md-12"> <label for="fullname">Full Name</label> <input type="text" class="bg-light form-control" placeholder="<?php echo htmlentities($userData->getFullName()); ?>" disabled> </div>
            </div>
            <div class="row py-2">
                <div class="col-md-6"> <label for="email">Email</label> <input type="text" class="bg-light form-control" placeholder="<?php echo htmlentities($userData->getEmail()); ?>" disabled> </div>
                <div class="col-md-6 pt-md-0 pt-3"> <label for="username">Username</label> <input type="tel" class="bg-light form-control" placeholder="<?php echo $userData->getUsername(); ?>" disabled> </div>
            </div>
            <div class="row py-2">
                <div class="col-md-6"> <label for="longitude">Longitude</label> <input type="text" class="bg-light form-control" placeholder="<?php echo htmlentities($userData->getLongitude()); ?>" disabled></div>
                <div class="col-md-6 pt-md-0 pt-3" id="latitude"> <label for="latitude">Latitude</label><input type="text" class="bg-light form-control" placeholder="<?php echo htmlentities($userData->getLatitude()); ?>" disabled></div>
            </div>
            <div class="d-sm-flex-wrap align-items-center pt-3" id="logout">
                <div>
                    <p>Logout from your account</p>
                </div>
                <div class="ml-auto"> <a class="btn danger btn-sm" href="logout.php">Logout </a> </div>
            </div>
        </div>
        <?php }} ?>
    </div>
</div>
<?php } else { ?>

<div id="notLoggedIn">
    <h1>You are not logged in!</h1>
</div>

<?php } ?>

<?php if (isset($_SESSION['error'])) unset($_SESSION['error']) ?>

<?php require('Template/footer.phtml') ?>
