<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- JS Form Validation Script -->
    <script defer type="module" src="../Scripts/register-form.js"></script>

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous"
    />

    <!-- Icon Fonts Stylesheet -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">

    <!-- My own css file  -->
    <link rel="stylesheet" href="/Styles/my-styles.css" type="text/css" />

    <title><?php echo $view->pageTitle; ?></title>
</head>
<body class="bg-light bg-gradient">
<div class="container">
    <!-- Responsive Container -->
    <div class="row vh-100 align-items-center justify-content-center">
        <div class="col-sm-8 col-md-6 col-lg-4 bg-white rounded p-4 shadow">
            <?php if (isset($_SESSION['error'])) { ?>
            <div class="alert alert-danger" role="alert">
                <?php echo $_SESSION['error']; ?>
            </div>
            <?php } ?>
            <div class="row justify-content-center mb-4">
                <!-- SVG Icon -->
                <svg xmlns="http://www.w3.org/2000/svg" height="42" fill="currentColor" class="bi bi-person-circle w-42" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/</div>
            <p class="text-center fw-light">Sign up to find and connect with people based on common interests, location and more. Already have an account? <a href="../Controller/login.php">Log in</a></p>
            <form id="registerForm" action="../Controller/register.php" method="POST">
                <div class="mb-4">
                    <label for="fullname" class="form-label">Full Name</label>
                    <i id="nameIcon" class="bi bi-check"></i>
                    <input type="text" class="form-control" id="fullname" name="fullname"  aria-describedby="fullnameHelp" >
                    <div id="fullnameHelp" class="form-text">Your full name</div>
                </div>
                <div class="mb-4">
                    <label for="email" class="form-label">Email Address</label>
                    <i id="emailIcon" class="bi bi-check"></i>
                    <input class="form-control" id="email" name="email" aria-describedby="emailHelp" >
                    <div id="emailHelp" class="form-text">Your valid email address</div>
                </div>
                <div class="mb-4">
                    <label for="username" class="form-label">Username</label>
                    <i id="userIcon" class="bi bi-check"></i>
                    <input type="text" class="form-control" id="username" name="username" aria-describedby="usernameHelp" >
                    <div id="usernameHelp" class="form-text">Your preferred username (This will be visible to others)</div>
                </div>
                <div class="mb-4">
                    <label for="password" class="form-label">Password</label>
                    <i id="passIcon" class="bi bi-check"></i>
                    <input type="password" class="form-control" id="password" name="password" aria-describedby="passwordHelp" >
                    <div id="passwordHelp" class="form-text">Password must be at least 6 characters long</div>
                </div>
                <!-- Anti-Spam feature/hidden input field only used by spammers -->
                <input type="text" id="spamInput" name="spamInput" class="d-none">
                <button type="submit" name="submit" class="btn btn-success w-100">Get Started!</button>
            </form>
        </div>
    </div>
</div>

<?php if (isset($_SESSION['error'])) unset($_SESSION['error']) ?>
</body>
</html>
